# Site settings
title: Reverse Vampires
email: d.krsnak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://reversevampire.github.io" # the base hostname & protocol for your site
github_username:  reversevampire

# Build settings
markdown: kramdown
